<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'titolo' => 'Colosseo',
                'descrizione' => 'Il più famoso anfiteatro romano, simbolo di Roma e patrimonio UNESCO.',
                'indirizzo' => 'Piazza del Colosseo, 1, 00184 Roma RM',
                'latitude' => 41.8902,
                'longitude' => 12.4922,
                'stato' => 'attivo',
                'orari_apertura' => 'Tutti i giorni 9:00-19:00 (ultimo ingresso 18:00)',
                'prezzo_biglietto' => '€18,00 - Ridotto €2,00',
                'sito_web' => 'https://colosseum.it',
                'telefono' => '+39 06 3996 7700',
                'note_visitatori' => 'Prenotazione consigliata. Disponibili visite guidate e audio-guide.',
            ],
            [
                'titolo' => 'Torre di Pisa',
                'descrizione' => 'La celebre torre pendente, uno dei monumenti più riconoscibili al mondo.',
                'indirizzo' => 'Piazza dei Miracoli, 56126 Pisa PI',
                'latitude' => 43.7230,
                'longitude' => 10.3966,
                'stato' => 'in_allarme',
                'orari_apertura' => 'Aprile-Settembre 9:00-20:00, Ottobre-Marzo 9:00-19:00',
                'prezzo_biglietto' => '€25,00 - Ridotto €20,00',
                'sito_web' => 'https://www.opapisa.it',
                'telefono' => '+39 050 835011',
                'note_visitatori' => 'Accesso limitato, prenotazione obbligatoria. Età minima 8 anni.',
            ],
            [
                'titolo' => 'Duomo di Milano',
                'descrizione' => 'Cattedrale gotica dedicata a Santa Maria Nascente nel cuore di Milano.',
                'indirizzo' => 'Piazza del Duomo, 20122 Milano MI',
                'latitude' => 45.4642,
                'longitude' => 9.1900,
                'stato' => 'attivo',
                'orari_apertura' => 'Lun-Dom 8:00-19:00. Terrazze: 9:00-19:00',
                'prezzo_biglietto' => 'Duomo: €3,00 - Terrazze: €15,00',
                'sito_web' => 'https://www.duomomilano.it',
                'telefono' => '+39 02 7202 3375',
                'note_visitatori' => 'Dress code richiesto. Accesso gratuito per la preghiera.',
            ],
            [
                'titolo' => 'Ponte di Rialto',
                'descrizione' => 'Storico ponte che attraversa il Canal Grande a Venezia.',
                'indirizzo' => 'Sestiere San Polo, 30125 Venezia VE',
                'latitude' => 45.4380,
                'longitude' => 12.3358,
                'stato' => 'attivo',
                'orari_apertura' => 'Sempre accessibile',
                'prezzo_biglietto' => 'Gratuito',
                'sito_web' => 'https://www.veneziaunica.it',
                'telefono' => '+39 041 2424',
                'note_visitatori' => 'Molto affollato durante l\'alta stagione. Migliori foto al mattino presto.',
            ],
            [
                'titolo' => 'Palazzo Pitti',
                'descrizione' => 'Imponente palazzo rinascimentale e complesso museale a Firenze.',
                'indirizzo' => 'Piazza de Pitti, 1, 50125 Firenze FI',
                'latitude' => 43.7651,
                'longitude' => 11.2497,
                'stato' => 'disattivo',
                'orari_apertura' => 'Mar-Dom 8:15-18:30 (chiuso lunedì)',
                'prezzo_biglietto' => '€16,00 - Ridotto €8,00',
                'sito_web' => 'https://www.uffizi.it/palazzo-pitti',
                'telefono' => '+39 055 2388611',
                'note_visitatori' => 'Biglietto combinato disponibile. Giardino di Boboli incluso.',
            ],
            [
                'titolo' => 'Castel del Monte',
                'descrizione' => 'Fortificazione del XIII secolo voluta da Federico II in Puglia.',
                'indirizzo' => '76123 Andria BT',
                'latitude' => 41.0838,
                'longitude' => 16.2710,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Arena di Verona',
                'descrizione' => 'Anfiteatro romano del I secolo, famoso per i concerti e opere liriche.',
                'indirizzo' => 'Piazza Bra, 1, 37121 Verona VR',
                'latitude' => 45.4386,
                'longitude' => 10.9952,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Palazzo Ducale',
                'descrizione' => 'Ex residenza dei Dogi di Venezia, capolavoro dell\'architettura gotica.',
                'indirizzo' => 'Piazza San Marco, 1, 30124 Venezia VE',
                'latitude' => 45.4335,
                'longitude' => 12.3405,
                'stato' => 'in_allarme',
            ],
            [
                'titolo' => 'Cattedrale di Palermo',
                'descrizione' => 'Maestosa cattedrale che fonde stili architettonici diversi.',
                'indirizzo' => 'Corso Vittorio Emanuele, 90134 Palermo PA',
                'latitude' => 38.1157,
                'longitude' => 13.3561,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Mole Antonelliana',
                'descrizione' => 'Edificio simbolo di Torino che ospita il Museo Nazionale del Cinema.',
                'indirizzo' => 'Via Montebello, 20, 10124 Torino TO',
                'latitude' => 45.0686,
                'longitude' => 7.6929,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Basilica di San Marco',
                'descrizione' => 'Basilica cattedrale patriarcale e santuario di Venezia.',
                'indirizzo' => 'Piazza San Marco, 328, 30124 Venezia VE',
                'latitude' => 45.4345,
                'longitude' => 12.3398,
                'stato' => 'disattivo',
            ],
            [
                'titolo' => 'Palazzo Reale di Napoli',
                'descrizione' => 'Storica residenza reale nel centro di Napoli.',
                'indirizzo' => 'Piazza del Plebiscito, 1, 80132 Napoli NA',
                'latitude' => 40.8359,
                'longitude' => 14.2488,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Cattedrale di Santa Maria del Fiore',
                'descrizione' => 'Duomo di Firenze con la famosa cupola del Brunelleschi.',
                'indirizzo' => 'Piazza del Duomo, 50122 Firenze FI',
                'latitude' => 43.7731,
                'longitude' => 11.2560,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Palazzo della Ragione',
                'descrizione' => 'Edificio medievale nel centro storico di Padova.',
                'indirizzo' => 'Piazza delle Erbe, 35139 Padova PD',
                'latitude' => 45.4077,
                'longitude' => 11.8749,
                'stato' => 'disattivo',
            ],
            [
                'titolo' => 'Teatro La Scala',
                'descrizione' => 'Uno dei teatri d\'opera più famosi al mondo.',
                'indirizzo' => 'Via Filodrammatici, 2, 20121 Milano MI',
                'latitude' => 45.4676,
                'longitude' => 9.1899,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Basilica di Sant\'Antonio',
                'descrizione' => 'Importante luogo di pellegrinaggio a Padova.',
                'indirizzo' => 'Piazza del Santo, 11, 35123 Padova PD',
                'latitude' => 45.4016,
                'longitude' => 11.8811,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Palazzo dei Normanni',
                'descrizione' => 'Palazzo reale di Palermo, sede dell\'Assemblea Regionale Siciliana.',
                'indirizzo' => 'Piazza Indipendenza, 1, 90129 Palermo PA',
                'latitude' => 38.1098,
                'longitude' => 13.3505,
                'stato' => 'in_allarme',
            ],
            [
                'titolo' => 'Palazzo Grassi',
                'descrizione' => 'Palazzo settecentesco a Venezia, oggi museo d\'arte contemporanea.',
                'indirizzo' => 'Campo San Samuele, 3231, 30124 Venezia VE',
                'latitude' => 45.4316,
                'longitude' => 12.3276,
                'stato' => 'attivo',
            ],
            [
                'titolo' => 'Cattedrale di Bologna',
                'descrizione' => 'Cattedrale metropolitana di San Pietro, principale chiesa di Bologna.',
                'indirizzo' => 'Via Indipendenza, 7, 40121 Bologna BO',
                'latitude' => 44.4970,
                'longitude' => 11.3426,
                'stato' => 'disattivo',
            ],
            [
                'titolo' => 'Palazzo Te',
                'descrizione' => 'Palazzo rinascimentale a Mantova, capolavoro di Giulio Romano.',
                'indirizzo' => 'Viale Te, 13, 46037 Mantova MN',
                'latitude' => 45.1521,
                'longitude' => 10.7965,
                'stato' => 'attivo',
            ],
        ];

        foreach ($locations as $location) {
            Location::create($location);
        }
    }
}
